baseURL : "http://Cynosure.page"
languageCode : "en-nz"
title : "Cynosure"
enableGitInfo: true

permalinks:
  blog: blog/:day-:month-:year/:title

markup:
  highlight:
    lineNos: true
    lineNumbersInTable: false
    anchorLineNos: true
    noClasses: false

taxonomies:
  tag: tags

security:
  exec:
    allow:
      - ^go$
      - ^asciidoctor$
