#!/bin/bash

# TODO handle better
IP=$(ip -4 -json addr show scope global | jq -r 'map(select(.ifname | test("docker.+") | not)) | .[].addr_info | .[].local')

# TODO Build
if [ "$1" = "serve" ]; then
	shift
	firefox --devtools "$IP:1313" &
	docker run -it -v "$PWD:/hugo" -p 1313:1313 -u "$(id -u):$(id -g)" website sh -c "hugo" "$@"
elif [ "$1" = "sh" ]; then
	docker run -it -v "$PWD:/hugo" -p 1313:1313 -u "$(id -u):$(id -g)" website sh
elif [ "$1" = "new" ]; then
	shift
	if [ ! -d "/content/$1" ]; then mkdir "/content/$1"; fi
	filename="/content/$1/$2.adoc"
	{
		echo "---"
		echo "draft: true"
		echo "title: ${1/-/ }"
		echo "date: $DATE"
		echo "summary: "
		echo "tags: "
		echo "  - "
		echo "---"
	} >> "$filename"
	$EDITOR "$filename"
else
	docker run -it -v "$PWD:/hugo" -p 1313:1313 -u "$(id -u):$(id -g)" website sh -c "hugo serve --bind 0.0.0.0 --baseURL=$IP --buildFuture" "$@"
fi
