---
title: How the Glitch Effect Works
summary: TLDR, stacked animations
tags:
  - meta
  - webdev
---

++++
	<div style="margin: 50px auto 50px auto; width: 90%">

		<input id="rainbow" type="checkbox" autocomplete="off" checked
		onChange="document.getElementById('editable').classList.toggle('rainbow')">

		<label for="rainbow">Rainbow text shadow</label>


		<br>
		<input id="pseudo" type="checkbox" autocomplete="off" checked
		onChange="
			document.getElementById('editable').classList.toggle('pseudo');
			if (!this.checked) {
				document.getElementById('wobble').disabled = true;
				document.getElementById('clipper').disabled = true;
				document.getElementById('overlay').disabled = true;
			} else {
				document.getElementById('wobble').disabled = false;
				document.getElementById('clipper').disabled = false;
				document.getElementById('overlay').disabled = false; }">

		<label for="pseudo">::before & ::after</label>

		<input id="pseudo-text" type="text" autocomplete="off" value="Edit Me"
		style="margin-left: 10px; width: 13ch"
		onInput="
			document.getElementById('editable').setAttribute('pseudo-text', this.value);
			if (this.value.trim() == '') {
				document.getElementById('wobble').disabled = true;
				document.getElementById('clipper').disabled = true;
				document.getElementById('overlay').disabled = true;
			} else if (document.getElementById('pseudo').checked) {
				document.getElementById('wobble').disabled = false;
				document.getElementById('clipper').disabled = false;
				document.getElementById('overlay').disabled = false; }">

		<br>
		<input id="overlay" type="checkbox" autocomplete="off"
		onChange="document.getElementById('editable').classList.toggle('overlay')">

		<label for="overlay">Highlight ::before & ::after</label>


		<br>
		<input id="wobble" type="checkbox" autocomplete="off" checked
		onChange="document.getElementById('editable').classList.toggle('wobble')">

		<label for="wobble">Wobbling</label>


		<br>
		<input id="clipper" type="checkbox" autocomplete="off" checked
		onChange="document.getElementById('editable').classList.toggle('clipper')">

		<label for="clipper">Moving clip-path</label>
	</div>

	<h2 id="editable" class="rainbow pseudo wobble clipper" contenteditable="true" pseudo-text="Edit Me";
	style="margin: 20px auto 50px auto; width: 90%">Edit Me Too</h2>


	<style id="styles">
		#editable {
			font-size: 5em;
			font-weight: 700;
			position: relative;
			margin: 0 auto;
			white-space: pre;
		}

		#editable::before,
		#editable::after {
			position: absolute;
			left: 3px;
			top: 0;
			opacity: 0.8;
			overflow: hidden;
			animation-delay: inherit;
			content: attr(pseudo-text);
		}

		#editable:not(.pseudo)::before,
		#editable:not(.pseudo)::after {
			display: none;
		}

		#editable.overlay::before,
		#editable.overlay::after {
			color: #999;
		}

		#editable.rainbow { animation: rainbow-text 1199ms infinite -200ms; }

		#editable.rainbow::after { animation: rainbow-text 375ms reverse infinite; }
		#editable.wobble::after { animation: wobble 957ms -500ms infinite reverse; }
		#editable.rainbow.wobble::after { animation: rainbow-text 375ms reverse infinite, wobble 957ms -500ms infinite reverse; }

		#editable.rainbow::before { animation: rainbow-text 650ms infinite alternate; }
		#editable.wobble::before { animation: wobble 1000ms infinite; }
		#editable.clipper::before { animation: clipper 1538ms linear -1500ms infinite alternate-reverse; }
		#editable.rainbow.wobble::before { animation: rainbow-text 650ms infinite alternate, wobble 1000ms infinite; }
		#editable.wobble.clipper::before { animation: wobble 1000ms infinite, clipper 1538ms linear -1500ms infinite alternate-reverse; }
		#editable.rainbow.clipper::before { animation: rainbow-text 650ms infinite alternate, clipper 1538ms linear -1500ms infinite alternate-reverse; }
		#editable.rainbow.wobble.clipper::before { animation: rainbow-text 650ms infinite alternate, wobble 1000ms infinite, clipper 1538ms linear -1500ms infinite alternate-reverse; }

	</style>
++++

I'm kinda proud of the effect. It's pretty dumb, and could definitely induce motion sickness if you stare at it for too long. But... It looks cool. It works through a combination of relatively simple animations layered together.
If there's no animation on the title, you may have reduced-motion set, or animations disabled on your device. Amusingly, I turn off animations on my phone so I can't see the effect.

Also, after far, far too long I am (just about) ready to say this site is at version 1.0. Hurrah.
{empty} +
{empty} +
{empty} +

== HTML
There are 2 things to see here.
Firstly, I set the content attribute to be equal to the title.
Secondly and unrelatedly, I vary the font size to make the title take up a reasonable amount of the page.


{{<highlight html "lineanchors=html, hl_lines=1">}}
<h1 class="glitch" content="{{ title .Title }}"
style="
	{{ if lt (len .Title) 20 }}
		font-size:15vmin
	{{ else if gt (len .Title) 60 }}
		font-size:8vmin
	{{ else }}
		font-size:{{ len .Title | math.Log | mul -7 | add 37 | math.Floor  }}vmin
	{{end}}"
>{{ title .Title }}</h1>
{{</highlight>}}


== CSS
This is largely unremarkable, just a load of animation keyframes.

Do pay attention to the content and animation delay attributes though. `content: attr(content)` is the trick that allows me to easily set the overlay text to match. This is important because I can easily set html content on a per page basis with Hugo (the static site generator I use), but it's substantially harder to have unique CSS per page.
`animation-delay` isn't useful for the majority of titles, but for the homepage I have each letter as its own separate animation. I've manually set a unique animation delay on each and that ensures the wandering clip paths don't all line up in an obvious way.

{{<highlight css "lineanchors=css, hl_lines=14-15">}}
@media (prefers-reduced-motion: no-preference) {
	.glitch {
		font-weight: 700;
		position: relative;
		animation: glitch-text 1199ms infinite -200ms;
	}

	.glitch::before,
	.glitch::after {
		position: absolute;
		left: 0;
		top: 0;
		opacity: 0.8;
		content: attr(content);
		animation-delay: inherit;
	}

	.glitch::before {
		animation: glitch-text 650ms infinite alternate,
			outer 1000ms infinite,
			before 1538ms linear -1500ms infinite alternate-reverse;
		clip-path: polygon(0 0, 100% 0, 100% 45%, 0 45%);
	}

	.glitch::after {
		animation: glitch-text 375ms reverse infinite, outer 957ms -500ms infinite reverse;
		clip-path: polygon(0 80%, 100% 20%, 100% 100%, 0 100%);
	}

	@keyframes glitch-text {
		0% {
			text-shadow: 0.05em 0 12px rgba(255, 0, 0, 0.75),
				-0.05em -0.025em 10px rgba(0, 255, 0, 0.75),
				-0.025em 0.05em 0 rgba(0, 0, 255, 0.75);
		}

		14% {
			text-shadow: 0.05em 0 0 rgba(255, 0, 0, 0.75),
				-0.05em -0.025em 0 rgba(0, 255, 0, 0.75),
				-0.025em 0.05em 0 rgba(0, 0, 255, 0.75);
		}

		15% {
			text-shadow: -0.05em -0.025em 0 rgba(255, 0, 0, 0.75),
				0.025em 0.025em 5px rgba(0, 255, 0, 0.75),
				-0.05em -0.05em 3px rgba(0, 0, 255, 0.75);
		}

		49% {
			text-shadow: -0.05em -0.025em 0 rgba(255, 0, 0, 0.75),
				0.025em 0.025em 0 rgba(0, 255, 0, 0.75),
				-0.05em -0.05em 0 rgba(0, 0, 255, 0.75);
		}

		50% {
			text-shadow: 0.025em 0.05em 0 rgba(255, 0, 0, 0.75),
				0.05em 0 0 rgba(0, 255, 0, 0.75),
				0 -0.05em 0 rgba(0, 0, 255, 0.75);
		}

		99% {
			text-shadow: 0.025em 0.05em 0 rgba(255, 0, 0, 0.75),
				0.05em 0 0 rgba(0, 255, 0, 0.75),
				0 -0.05em 0 rgba(0, 0, 255, 0.75);
		}

		100% {
			text-shadow: -0.025em 0 5px rgba(255, 0, 0, 0.75),
				-0.025em -0.025em 0 rgba(0, 255, 0, 0.75),
				-0.025em -0.05em 12px rgba(0, 0, 255, 0.75);
		}
	}

	@keyframes outer {
		0% {
			opacity: 30%;
		}

		14% {
			opacity: 20%;
			transform: translate(-0.04em, -0.026em);
		}

		15% {
			opacity: 100%;
			transform: translate(0.02em, 0.016em) rotate(-0.5deg);
		}

		49% {
			transform: rotate(0.1deg);
			opacity: 80%;
		}

		50% {
			transform: rotate(-0.2deg);
		}

		60% {
			transform: rotate(0.1deg) translate(0.015em, 0.002em);
			opacity: 40%;
		}
	}

	@keyframes before {
		0% {
			clip-path: polygon(0 0, 100% 0, 100% 45%, 0 45%);
		}

		20% {
			clip-path: polygon(0 0, 100% 0, 100% 45%, 0 75%);
		}

		22% {
			clip-path: polygon(0 0, 100% 0, 100% 35%, 0 25%);
		}

		75% {
			clip-path: polygon(0 0, 100% 0, 100% 35%, 0 25%);
		}

		76% {
			clip-path: polygon(0 0, 100% 0, 100% 5%, 0 75%);
		}
	}
}
{{</highlight>}}
