---
draft: true
title: Predictions for the Future-Future of AR
date: 2024-03-16
summary: I have no experience, and a lot of thoughts.
tags: 
  - tech
  - AR
---

I am sick of working at a desk. When I can code while sitting outside under a tree with the gear I wear every day, I will be happy. I have a few ideas about that world, and like an ancient Greek philosopher I shall proclaim them.

== Passive Information

Ubiquitous computing is an idea that has been around for decades, but has never taken off. Part of that is due to the difficulties of visualising the data.
The usual solution is to setup a tiny screen somewhere. They suck. The UI is a nightmare, the hardware is underpowered, the software is outdated, and they're never where you need them.

I hope AR tech can solve this.
With a standard for smart sensors, we can enable

Flexibility of user driven software - Cambrian explosion of creativity
Cars
Menus
Batman tactical view
The difference between passively seeing something, and having to pull out your phone is the difference between a phone and a desktop. Information is an order of magnitude closer.

Perhaps this is just me wishcasting. I've managed to rip myself of social media (mostly). I've found a better way to use the internet. AR is likely to be even more engrossing.

Also more decentralisation coming

== Going beyond taps

Apple's eye based controls seem cool and all, if you have control over where you look (which is not a given), and you only ever need to input one thing at a time directly where you're looking, and you only ever intend to use it in situations where you don't have other things to look at (like traffic). I just think, maybe, there are situations where it's not ideal.

And even if you are in the ideal situations, it strikes me as unbelievably clunky for text input. For now, while people primarily use Visions at a desk near a power plug, they can just use a keyboard and cope. But there are 2 problems with this.
1.	You need to have a keyboard. Apple is clearly working towards glasses that can be worn anywhere, every day. That means out in the world without a keyboard handy.
2.	It's leaving so much interaction on the table. Our hands are wonderfully expressive, dynamic, and sensitive. They're capable of so many movements, and can sense fine details. Merely clicking, when there are 3 dimension of input (first knuckle, second knuckle, left/right (most people don't have enough control of the last knuckle to be useful)), across 2 hands, each with 5 fingers (maybe not all of them equally useful), is irritating.

This system will be easy to develop for, it's a similar design language as the other digital user interfaces we're used to. But it shouldn't be. Those design systems are for 2d interfaces, but the key conceit of AR/VR is the 3rd dimension.

The thing this reminds me of most is multitouch. It's very cool, very elegant. But no one is writing a novel on a phone. No one is doing serious programming on a mobile.

== Haptics

Input when you're looking at something else
Affordances
Contribute to illusion

== Goodbye to designer glasses

Once people have smart glasses I doubt they're going to go back to smart glasses in day to day life. Smart glasses are too useful, it'll be too much of a hassle to switch back and forth, and a large part of the value of smart glasses comes from the information they make passively visible.
The difficulty of designing smart glasses means that there are going to be far fewer companies capable of designing smart glasses than dumb glasses. We can look at cars, which are similarly difficult to design and constrained by the limits of technology. In the mid-market similar designers with similar resources and similar constraints have lead to similar styling. The constraints for smart glasses will come from the layout of the projection system and how small the electronics can get, so goodbye to wire frames (my favourite).
Perhaps we'll get some customisation options equivalent to swapping watch straps, probably changing the colour of the arms. At a stretch we might get interesting cutouts or contorted PCBs, but I doubt there's the market for it.
Everyone will be wearing the same designs, all the time. This sucks. Glasses can radically change how a face looks, and, at least for me, are worn all the time for years between replacements. They are the most important fashion decision a person makes, and that's all going to be lost.

== Halos

It's going to be extremely difficult to condense everything into a glasses form factor, even if the glasses are chunky. What I think is much more likely is either tethered compute pucks like we've seen with the vision pro. I think someone will try making the puck into a neckband, like with some earbuds. And if I were to guess, they'll be called Halos.
