---
title: Predictions for the Future-Future of XR
date: 2024-03-16
summary: I have little experience, and a lot of thoughts.
tags: 
  - tech
  - AR
---

I am sick of working at a desk.
I want to be able to sit under a tree and program without carrying specialised equipment.
Only then will I be happy.
I have a few ideas about that world, and like an ancient Greek philosopher I shall proclaim the intuitive truth of them.

== AR's killer app is Passive Information

The proclaimed killer app for people who actually use AR is virtual desktops.
That's because the early adopters are overwhelmingly white-collar workers.
For people in service industries they're working with their hands so digital interfaces aren't where the work is done, they're where the work is coordinated.
More screen space doesn't mean better coordination.
What does help is putting the information where they need it.
This looks like arrows on the ground for delivery drivers, highlighting already covered areas for cleaners, tagging spills for people in stores.
For nurse it means patient information floating beside the patient so they maintain a human connection, for builders it means a digital twin to match work to rather than triple checking plans.

There is a dark side, virtual billboards.
I'm counting on adblock though.

Under this conception the digital world isn't a tool and it isn't a place, it's a field that overlays all of reality.
Information is an order of magnitude closer, so it's an order of magnitude more useful.
AR : Phones :: Phones : Desktops

Plenty of people are concerned about becoming even more addicted to their devices, but this seems unlikely.
For active consumption, such as scrolling tiktok, a phone is already quick to open and sufficient to distract you.
There is some chance that people will be reminded of social media more often and with the marginal increase in ease will therefore open those apps more.
That seems fairly marginal, given that everyone who has made that argument to me already use their devices whenever they can.
To be clear, I don't think AR will help but I don't think it will make things worse.
I can see arguments that smart glasses will make it easier to surreptitiously slack off, but I don't think this is a big concern outside of schools.
More and more countries are banning phones in school, I imagine smart glasses will follow quite quickly.

The key thing about AR is that it's __augmenting__ reality, not replacing it.
Perhaps it's too optimistic of me but I think AR will help connect us to the real world rather than distract us with a shallow impression.


== Going beyond taps

Apple's eye based controls seem cool and all, assuming you have control over where you look (which is not a given), and you only ever need to input one thing at a time directly where you're looking (which isn't always the case).
I just think, maybe, there are situations where it's not ideal.
Even if you are in the ideal situations, it strikes me as unbelievably clunky for text input. For now people just use a keyboard and cope.
But there are 2 problems with this:

. You need to have a keyboard.
Apple is clearly working towards glasses that can be worn anywhere, every day.
That means out in the world without a keyboard handy.

. It's leaving so much interaction on the table.
Our hands are wonderfully expressive, dynamic, and sensitive, they're capable of so many movements, and can sense fine details and all of this is left to waste.
When XR objects feel so close to real the interaction gap will be maddening and frustrating.

This system is clearly chosen because it's similar to tapping which users and designers are familiar with.
But those systems are for 2d interfaces, and a key conceit of XR is the 3rd dimension.
The ability to click and drag files, Direct Manipulation, was a leap forwards for usability.
In XR the intuitive thing is to grab a file by grasping with your hand, rather than to tapping and dragging.

== Goodbye to designer glasses

Once people have smart glasses I doubt they're going to go back to dumb glasses in day to day life.
Smart glasses are too useful, it'll be too much of a hassle to switch back and forth, and it's not worth carrying (and potentially loosing) multiple pairs.
The difficulty of designing smart glasses means that there are going to be far fewer companies capable of designing smart glasses than dumb glasses.
Even among the companies that can design then we can look to cars, which are similarly difficult to design and as constrained by the limits of technology.
In the mid-market similar designers with similar resources and similar constraints have lead to similar styling.
The constraints for smart glasses will come from the layout of the projection system and how small the electronics can get, so goodbye to wireframes (my favourite).
Perhaps we'll get some customisation options equivalent to swapping watch straps, perhaps changing the colour of the arms. At a stretch we might get interesting cutouts or contorted PCBs for promotional attempts.
Everyone will be wearing the same designs, all the time.
This sucks.
Glasses can radically change how a face looks, and, at least for me, are worn all the time for years between replacements.
They are the most important fashion decision a person makes, and that's all going to be lost beneath a sea of bulky black frames.

== Invisible IR QR codes

There will be a need to add basic smart functionality to regular objects, I imagine this will be done with transparent QR code stickers that show up in IR.
TODO:[IR-opaque ink] is available and can be used in a standard printer, and TODO:[transparent sticker material] is cheap.
Plenty of smart glasses have IR cameras for depth sensing (TODO verify), so this wouldn't require any extra hardware.
When I get the time I plan to make these, I don't think they'll be too difficult.

== Halos

It's going to be extremely difficult to condense everything into a glasses form factor, even if the glasses are chunky.
What I think is much more likely is tethered compute pucks.
I think someone will try making the puck into a neckband as with some earbuds, and if I were to guess, they'll call them Halos.
