---
draft: true
title: A year spent vibrating fingers
date: 2025-12-22
summary: I think I enjoyed my honours, I can't really tell
tags: 
  - Personal
  - AR
---

It's not that I think HCI is boring, I just think it's a decade behind where it ought to be.
I've got a vision for the future of keyboards and I plan to make it a reality.
About a month ago I finished my honours, in which I tested one of the key parts of my vision.

I believe the best system is a virtual keyboard which can be used on any surface, including the typist's legs.
As I have link:{{% ref "2025-07-06-XR-Typing" %}}[detailed before] text input methods for AR are underresearched, and what does exist is slow, unpleasant, and wholly unsuitable for extended daily use.
It will be a long time before keyboards are usurped, and we need a AR-native keyboard
I link:{{% ref "2025-06-06-Typing-Critera" %}}[outlined] a number of properties an AR keyboard will need, and from these we can find the solution space.

'''
== An informal summary of my report

For my honours project I aimed to test the value of haptic feedback for typing.
Haptics requires a substantial increase in bulk and complexity, hand tracking can be done using cameras or EMG but haptics requires hardware on the typist's hands.
However, there is compelling evidence that haptics matter to typists, and it's likely to be even more important when typing on inconsistent surfaces such as a wooden table or cloth-covered-legs.

Notably I didn't test on the surfaces a virtual keyboard would be used on because my testing methodology required a traditional keyboard to register keypresses.
There are already models to convert finger motion to keypresses but they only work on flat surfaces, for my masters I'm planning to extend these to work on any surface.
I had some reason to do the haptics first, but seeing as I don't remember what that reason is it can't be very good.
Unfortunately, because I didn't test on relevant surfaces my results aren't particularly useful because it's unclear how much they generalise.

== Past Evidence
Lots on traditional keyboards, muddier for XR

== My contribution
On-finger
TBH more about learning

== Methods

== Results

== Future work
Masters
Rework hardware
Combine and measure


'''
== Extra stories from the year

Horrendous fucking serial bug
  still no clue
  kinda a vibey life

Frontend tooling
  multiple versions
  reflections