---
draft: true
title: 'Debating Lessons: Listening'
date: 2025-07-17
summary: 
tags: 
  - debating
---

At time of writing I am the 19th best debater in New Zealand. One of the great things about debating is that so many skills transfer to other parts of life, and debating is the most enjoyable way to learn them.

Today I'll talk about listening and note taking.

Most people assume that good debaters need (delusional) levels of self confidence, that they're chatterboxes with overbearing personalities. That is false. In my experience, the best debaters are often careful and attentive listeners. They can listen to someone's opinion without forcing their perspective.
It's just as much about what you say as how you say it. You don't have time to talk about everything so need to prioritise. Be prepared.

It doesn't matter how smart you sound or how right you are, if you ignore the opposition you will loose. You need to understand what they're saying to explain why they're wrong. When you're caught up in the moment it can be difficult to break out of your perspective. Obviously the opposition is wrong from your perspective, but that's not the one that matters, it's the judge's that counts. As a judge it's extremely obvious when a speaker doesn't really understand their opposition, they argue at a surface level, often arguing against a slightly different case than the opposition presented.


== Listening

The two most common mistakes people make are taking too many notes, and assuming they heard everything.
Humans can't multitask, the closest we can get is to switch back and forth between tasks quickly. This means time spent writing is time not spent listening. When we switch tasks there's a moment in between where our brains have to drop the old information and get set up for the new context. This makes people miss even more.
It's much more important to listen than it is to take notes, if you don't hear something you have no hope of remembering it in future, no matter how good your notes are. Often people listen to the first few words, assume they know what the speaker is saying, and tune out the rest. This usually goes badly.
If a speaker tells you something is important, listen to them. Even if it turns out to be useless, the fact they think it's important should tell you a lot about how they are thinking.
Sometimes you have no choice but to tune out for a moment to take notes, if you're aware that's what you're doing you can pick the right time. If the speaker pauses for a moment that's a good time to take notes. It's even better if you know what they're going to say, because you have an idea of what's going to be important.

Preparation is the key. In debating there's prep time, and good debaters will spend a few minutes thinking of the likely opposition case at a high level, with time debaters can do this faster and go into more depth, they can also think of possible offbeat cases, a lot of debating is recognising similarities to previous debates. In all speeches, good speakers will give a short introduction at the start summarising what they're going to cover.
When you have an idea of what a speaker is going to talk about you can understand them better. Knowledge is like a web, you need to understand how it all connects together. If you're spending your time trying to figure out how each fact connects to the others you have less time to think about what the speaker is saying. The speaker's introduction tells you how the facts fit together and why they matter.
Sometimes you'll be surprised. Those are the most important parts of the speech, because that's where there's the most difference between you and the speaker. That means you can learn the most, or you can create the biggest difference between you and the speaker.

If you write questions in advance you'll realise the answers as the speaker gets to them. This is more efficient than trying to think back later. It also helps you pay attention because there's now a specific reason to listen, rather than a vague goal of 'understanding'. Listening with a purpose is good.
Common questions include:
	What are they trying to do/argue for? Be as specific as possible?
	How does that affect you? How much?
	What do they think the alternatives are? Are there options they haven't considered?
	How do they think the world works? How do they assume others will respond?
	Who/what do they think is relevant? Is there anyone else you could bring into the discussion?




Think about it from their perspective
	Take them at their best
	What do they think is important
	Why?

	Be charitable. Even if you disagree, it's always good to 
		hype them up, you look strong
		maybe more similar than you think
		Looks good that you really tried their way

Finally, remember that being so dialed in isn't easy, and it takes practice. Even then continued focused listening is exhausting. This should be obvious, but I know I always need a reminder. Get rid of things which could distract you, mute notifications, I find sunglasses help me but obviously that's not always an option. Look after your body, eat food, drink water, get sleep, and if you have a long day of intense thinking drink electrolytes.
If you're not mentally present then nothing else matters, because listening is so much more than just sound waves hitting your ears. Your brain needs to do work to decode the ideas and process them.


== Note taking

As I said, you can't multitask so alternate listening and writing, and if you're with someone else take turns listening and writing notes, then swap.

The most common mistake beginners make is trying to write down everything they say. You will fall behind and while you're stressing and trying to remember what they said you'll miss something. The only purpose of notes is to remind you what happened, so you should only write down a few key words to jog your memory. This is why listening is more important, if you listen you'll remember what they said, have time to think about it, and then can go off a few words or sentences. If you focus on note taking you'll have to read off your notes which will inhibit your thinking.

Remember that live notes are for you to remember things in the short term. In a debate it's at most 30 minutes until your speech. In a meeting or lecture the notes only need work until the end.
If you need the notes to be useful later, or if they're going to be read by someone else you can go over the live note afterwards and fill in the missing details.

Notes are more than just the words they hold. Use arrows, symbols, colors, acronyms, highlighters, layout, multiple pages. Anything you can do to get the same information down in less time is good. In debates I use three pens: blue, red, and black; blue for what we say, red for what they say, and black for high level thoughts (or feedback if I'm judging). I then have a handful of symbols for the different parts of a speech. If something is important I put a box around it. For each point in a speech I use at least one piece of paper, this helps me keep them distinct, and when I go to speak I can lay out the pages so that they layout of my notes reflects the structure of my speech.
Be careful with arrows, when used judiciously they are excellent, but if you overuse them everything will become a spaghetti mess.
Some people work better with unlined paper, I prefer lined. You should experiment with both.
Post-its are an excellent tool if you're working with someone else, or if you need to add layers to your notes as the speaker goes on.
