---
title: "The Disappearance of Tween Fashion [Archive Pull] [archive]"
media_id: " 1000756180670"
media_type: "podcast"
layout: "archive"
archived: "2026-06-23"
date: "2026-03-19"
series: "Never Post"
original_url: "https://podcasts.apple.com/nz/podcast/the-disappearance-of-tween-fashion-archive-pull/id1719307150?i=1000756180670"
media_file: "1000756180670.mp3"
thumbnail: "1000756180670.jpg"
---

== Description

Originally published in our first episode I'm Mad, You're Mad, We're All Mad Here on January 31, 2024, enjoy Georgia's segment talking to Professor Elizabeth Wissinger about how the social internet helped erase an entire fashion demographic — namely, tween fashion for girls.
Listen to the original episode here: https://www.neverpo.st/never-post-2/
–
Become a Never Post member at https://www.neverpo.st/ for an ad-free version of the show and bonus content
–
Find Elizabeth Wissinger: Her website This Year's Model: Fashion, Media, and the Making of Glamour – Call us at 651 615 5007 to leave a voicemail Drop us a voice memo via airtable  Or email us at theneverpost at gmail dot com –
Never Post’s producers are Audrey Evans, Georgia Hampton and The Mysterious Dr. Firstname Lastname. Our senior producer is Hans Buetow. Our executive producer is Jason Oberholtzer. The show’s host is Mike Rugnetta.
–
Never Post is a production of Charts & Leisure and is distributed by Radiotopia
